---
ruler_x: 0
ruler_y: 1062
ruler_length: 3839
track_mouse: true
metric: 1
keep_above: true
foreground_color: "#202020"
background_color: "#e6e36b"
font: Sans 20
opacity: 0.85
use_custom_pixels_per_inch: true
horizontal_pixels_per_inch: 282.0
vertical_pixels_per_inch: 282.0
